schema_version = "1.0.0"

# VSE Generative Media Bridge Extension Manifest
# A bridge between Blender's VSE and external generative tools

id = "vse_generative_media_bridge"
version = "1.0.0"
name = "VSE Generative Media Bridge"
tagline = "Run external generative media tools directly from Blender's VSE"
maintainer = "Paul <ttaacchhyyoonn+vsegmb.com>"
type = "add-on"

# Optional: link to documentation, support, source files, etc
website = "https://github.com/if-paul-then/BlenderVSEGenerativeMediaBridge"

# Optional: tag list defined by Blender and server
tags = ["Sequencer", "Pipeline"]

blender_version_min = "4.2.0"
# Optional: Blender version that the extension does not support, earlier versions are supported.
# blender_version_max = "5.1.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX:" prefix)
license = [
  "SPDX:GPL-3.0-or-later",
]

# Optional: required by some licenses.
# copyright = [
#   "2025 Paul & Joshua",
# ]

# Optional: list of supported platforms. If omitted, the extension will be available in all operating systems.

# Optional: bundle 3rd party Python modules.
wheels = [
  "./wheels/strictyaml-1.7.3-py3-none-any.whl",
  "./wheels/python_dateutil-2.9.0.post0-py2.py3-none-any.whl",
  "./wheels/six-1.17.0-py2.py3-none-any.whl",
]

# Optional: add-ons can list which resources they will require:
# * files (for access of any filesystem operations)
# * network (for internet access)
# * clipboard (to read and/or write the system clipboard)
# * camera (to capture photos and videos)
# * microphone (to capture audio)
#
# For each permission it is important to also specify the reason why it is required.
# Keep this a single short sentence without a period (.) at the end.
# For longer explanations use the documentation or detail page.

[permissions]
files = "Read/write media files and execute external generative tools"

# Optional: advanced build settings.
[build]
# These are the default build excluded patterns.
# You only need to edit them if you want different options.
paths_exclude_pattern = [
  "__pycache__/",
  "/.git/",
  "/*.zip",
  "/tests/",
  "/docs/",
  "*.pyc",
  "*.pyo",
  ".DS_Store",
  "Thumbs.db",
  "/.vscode/",
  "/.idea/",
  "/requirements.md",
  "/impl_plan.md",
] 